package pojo;
// Generated Oct 12, 2022 5:54:53 PM by Hibernate Tools 4.3.1

import DAO.DAOBook;
import java.util.List;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;




/**
 * TblBook generated by hbm2java
 */
@ManagedBean (name = "TblBook")
public class TblBook  implements java.io.Serializable {


     private Integer id;
     private String title;
     private String author;
     private String genre;
     private String synopsis;
     private String cover;
     private int price;
     private List<TblBook> bookList;
     private String SuccessMsg = null;
     private String ErrorMsg = null;
     
     public TblBook(String title, String author, String genre, String synopsis, String cover, int price) {
       this.title = title;
       this.author = author;
       this.genre = genre;
       this.synopsis = synopsis;
       this.cover = cover;
       this.price = price;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getAuthor() {
        return this.author;
    }
    
    public void setAuthor(String author) {
        this.author = author;
    }
    public String getGenre() {
        return this.genre;
    }
    
    public void setGenre(String genre) {
        this.genre = genre;
    }
    public String getSynopsis() {
        return this.synopsis;
    }
    
    public void setSynopsis(String synopsis) {
        this.synopsis = synopsis;
    }
    public String getCover() {
        return this.cover;
    }
    
    public void setCover(String cover) {
        this.cover = cover;
    }
    public int getPrice() {
        return this.price;
    }
    
    public void setPrice(int price) {
        this.price = price;
    }

    public List<TblBook> getBookList() {
        return bookList == null ? this.getAllRecords() : bookList;
    }

    public void setBookList(List<TblBook> bookList) {
        this.bookList = bookList;
    }

    public String getSuccessMsg() {
        return SuccessMsg;
    }

    public void setSuccessMsg(String SuccessMsg) {
        this.SuccessMsg = SuccessMsg;
    }

    public String getErrorMsg() {
        return ErrorMsg;
    }

    public void setErrorMsg(String ErrorMsg) {
        this.ErrorMsg = ErrorMsg;
    }
    
    public List<TblBook> getAllRecords(){
         DAOBook pdk = new DAOBook();
         List<TblBook> iPdk = pdk.retrveProduk();
         
         return iPdk;
     }
     
     public String getById(){
         String id_produk = id.toString();
         DAOBook pdk = new DAOBook();
         List<TblBook> lPdk = pdk.getbyID(id_produk);

         try {
             if (lPdk !=null) {
                 title = lPdk.get(0).title;
         author = lPdk.get(0).author;
         genre = lPdk.get(0).genre;
         synopsis = lPdk.get(0).synopsis;
         cover = lPdk.get(0).cover;
         price = lPdk.get(0).price;
                 System.out.println(title);
                 System.out.println(price);
                 return "dahsboard";
             }
             
         } catch (Exception e) {
             System.out.println(e);
         }
         setErrorMsg("Comic data that you've entered are invalid");
         return "error";
     }
     
     public String getProduk(){
         String id_produk = id.toString();
         DAOBook pdk = new DAOBook();
         List<TblBook> lPdk = pdk.getbyID(id_produk);
       
         title = lPdk.get(0).title;
         author = lPdk.get(0).author;
         genre = lPdk.get(0).genre;
         synopsis = lPdk.get(0).synopsis;
         cover = lPdk.get(0).cover;
         price = lPdk.get(0).price;
         
         return "detailedPage";
     }
     
    public void edit(){
         DAOBook pdk = new DAOBook();
         pdk.editProduk(this);
         
         title = "";
         author = "";
         genre = "";
         synopsis = "";
         cover = "";
         price = 0;
         FacesMessage facesMessage = new FacesMessage(FacesMessage.SEVERITY_INFO,"Berhasil Update!",null);
     }

    public  void delete(){
         DAOBook pdk = new DAOBook();
         pdk.deleteProduk(id);
         
         title = "";
         author = "";
         genre = "";
         synopsis = "";
         cover = "";
         price = 0;
    }
    
    public String save_produk (){
        DAOBook add = new DAOBook();
        add.add_produk(this);
        this.Clear();
        return "dahsboard";
        
    }
    
    public void Clear() {
        id = null;
        title  = "";
        author  = "";
        genre  = "";
        synopsis  = "";
        cover  = "";
        price  = 0;
    }
     
     
     
    public TblBook() {
    }

    
    
    
    


}


