package pojo;
// Generated Oct 12, 2022 5:54:53 PM by Hibernate Tools 4.3.1

import DAO.DAOLogin;
import java.util.List;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;




/**
 * TblUser generated by hbm2java
 */
@ManagedBean
public class TblUser  implements java.io.Serializable {


     private Integer idUser;
     private String username;
     private int noTelp;
     private String email;
     private String password;
     private String address;
     
     public String login_user(){
         DAOLogin uDao = new DAOLogin();
         List<TblUser> tu = uDao.getBy(username, password);
         
         try{
             if(tu != null){
             username = tu.get(0).username;
             password = tu.get(0).password;
             return "dahsboard";
            }
         }
         catch (Exception e){ 
             System.out.println(e);
         }
         return "gagal_login";
     }

    public TblUser() {
    }

    public TblUser(String username, int noTelp, String email, String password, String address) {
       this.username = username;
       this.noTelp = noTelp;
       this.email = email;
       this.password = password;
       this.address = address;
    }
   
    public Integer getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(Integer idUser) {
        this.idUser = idUser;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public int getNoTelp() {
        return this.noTelp;
    }
    
    public void setNoTelp(int noTelp) {
        this.noTelp = noTelp;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }




}


